name: Build with Theos

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build
        run: |
           mv xpc $THEOS/include/xpc
           sh gen_asm.sh
           sh release_build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Items
          path: ./packages
